def main():
    camelCase = input("camelCase: ")
    for letter in camelCase:
        if letter == "A":
            camelCase = camelCase.replace("A", "_a")
        if letter == "B":
            camelCase = camelCase.replace("B", "_b")
        if letter == "C":
            camelCase = camelCase.replace("C", "_c")
        if letter == "D":
            camelCase = camelCase.replace("D", "_d")
        if letter == "E":
            camelCase = camelCase.replace("E", "_e")
        if letter == "F":
            camelCase = camelCase.replace("F", "_f")
        if letter == "G":
            camelCase = camelCase.replace("G", "_g")
        if letter == "H":
            camelCase = camelCase.replace("H", "_h")
        if letter == "I":
            camelCase = camelCase.replace("I", "_i")
        if letter == "J":
            camelCase = camelCase.replace("J", "_j")
        if letter == "K":
            camelCase = camelCase.replace("K", "_k")
        if letter == "L":
            camelCase = camelCase.replace("L", "_l")
        if letter == "M":
            camelCase = camelCase.replace("M", "_m")
        if letter == "N":
            camelCase = camelCase.replace("N", "_n")
        if letter == "O":
            camelCase = camelCase.replace("O", "_o")
        if letter == "P":
            camelCase = camelCase.replace("P", "_p")
        if letter == "Q":
            camelCase = camelCase.replace("Q", "_q")
        if letter == "R":
            camelCase = camelCase.replace("R", "_r")
        if letter == "S":
            camelCase = camelCase.replace("S", "_s")
        if letter == "T":
            camelCase = camelCase.replace("T", "_t")
        if letter == "U":
            camelCase = camelCase.replace("U", "_u")
        if letter == "V":
            camelCase = camelCase.replace("V", "_v")
        if letter == "W":
            camelCase = camelCase.replace("W", "_w")
        if letter == "X":
            camelCase = camelCase.replace("X", "_x")
        if letter == "Y":
            camelCase = camelCase.replace("Y", "_y")
        if letter == "Z":
            camelCase = camelCase.replace("Z", "_z")
    print(camelCase)

main()
